export type Model = {
  slug: string;
  name: string;
  series: string;
  seriesSlug: string;
  tagline: string;
  description: string;
  startingPrice: number;
  area: string;
  areaSqft: string;
  dimensions: string;
  guests: string;
  weight: string;
  power: string;
  delivery: string;
  features: string[];
  exterior: string[];
  interior: string[];
  catalogImage: string;
  accent: string;
  finish: string;
  badge?: string;
};

export type Series = {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  hero: string;
  silhouette: string;
};

const img = (n: number) =>
  `/TERRA%20PODS%20CATALOG%202028-images-${n}.jpg`;

export const series: Series[] = [
  {
    slug: "a",
    name: "A Series",
    tagline: "The signature capsule",
    description:
      "Our defining capsule silhouette — a pearl-white aluminium shell, panoramic glazing, and a softly curved roofline. Available in four lengths, from a 16 m² studio to a 45 m² flagship.",
    hero: img(4),
    silhouette: img(1),
  },
  {
    slug: "h",
    name: "H Series",
    tagline: "Aerodynamic clarity",
    description:
      "A sculpted leading edge and ribbon glazing. The H Series reads as a single quiet gesture, anchored by a panoramic skylight.",
    hero: img(6),
    silhouette: img(6),
  },
  {
    slug: "r",
    name: "R Series",
    tagline: "Open-air, panoramic",
    description:
      "The R Series adds a stainless steel entrance door and a panoramic balcony — engineered for sites where the view earns its keep.",
    hero: img(8),
    silhouette: img(7),
  },
  {
    slug: "p",
    name: "P Series",
    tagline: "Linear precision",
    description:
      "Long, low, and luminous. The P Series balances a continuous glazed elevation against a quiet aluminium spine.",
    hero: img(10),
    silhouette: img(9),
  },
  {
    slug: "z",
    name: "Z Series",
    tagline: "Architectural minimalism",
    description:
      "Tightly composed proportions with a hard horizon line. Suited to clients who want the pod to disappear into the site.",
    hero: img(12),
    silhouette: img(11),
  },
  {
    slug: "f",
    name: "F Series",
    tagline: "Glass-forward",
    description:
      "A glass-forward elevation and a cantilevered shoulder. F is the most transparent expression in the collection.",
    hero: img(5),
    silhouette: img(5),
  },
  {
    slug: "e",
    name: "E-II Series",
    tagline: "The evolution",
    description:
      "The second-generation E shell — a refined snout, deeper insulation, and a continuous interior datum line. Available in four lengths.",
    hero: img(16),
    silhouette: img(13),
  },
  {
    slug: "w",
    name: "W Series",
    tagline: "Squared, residential",
    description:
      "A more residential proposition. Squared corners, a flat roofline, and a generous interior volume — the W reads as architecture, not as a pod.",
    hero: img(19),
    silhouette: img(17),
  },
  {
    slug: "specialty",
    name: "Specialty",
    tagline: "Service & dining",
    description:
      "Hospitality-grade capsules in our oxide-red finish. Configured as a guest service center or a fully equipped dining room — engineered to land beside your accommodation pods.",
    hero: img(21),
    silhouette: img(20),
  },
  {
    slug: "ae",
    name: "AE Cabin Series",
    tagline: "Modular cabin architecture",
    description:
      "A panelised cabin system. Solar-ready roof, tempered Low-E glazing, and a kit-of-parts wall module that ships flat and assembles in days.",
    hero: img(25),
    silhouette: img(22),
  },
];

const baseExterior = [
  "Galvanized steel structural frame",
  "Fluorocarbon-sprayed aluminium alloy shell",
  "Three-layer hollow tempered floor-to-ceiling glass",
  "Thermal, waterproof and moisture-proof envelope",
];

const balconyExterior = [
  ...baseExterior,
  "Painted stainless steel swing entrance door",
  "Panoramic balcony",
  "Hollow laminated tempered glass skylight",
];

const baseInterior = [
  "Integrated ceiling and wall stone modules",
  "Crystal wood-grain flooring",
  "Marble / tile bathroom",
  "Branded smart toilet",
  "Whole-house smart lighting",
  "Air conditioner (cooling & heating)",
  "Electric underfloor heating",
];

const smartInterior = [
  ...baseInterior,
  "Multi-scenario mode function panel",
  "Smart voice control",
  "Hotel-grade access control",
];

export const models: Model[] = [
  {
    slug: "a3",
    name: "Terra Pod A3",
    series: "A Series",
    seriesSlug: "a",
    tagline: "The studio capsule",
    description:
      "A compact 16 m² capsule for two — a single luminous volume with a full bath, integrated bed, and a wall of tempered glass that erases the boundary between you and the site.",
    startingPrice: 47500,
    area: "15.7 m²",
    areaSqft: "169 sq ft",
    dimensions: "5600 × 2800 × 3100 mm",
    guests: "2 guests",
    weight: "≈4 t (with floor heating)",
    power: "6.7 kW · 11.2 kW peak",
    delivery: "10 weeks",
    features: [
      "Floor-to-ceiling tempered glass",
      "Integrated bed platform",
      "Full marble bath",
      "Smart access control",
      "Solar-ready electrical",
    ],
    exterior: baseExterior,
    interior: baseInterior,
    catalogImage: img(1),
    accent: "from-amber-500/20 to-transparent",
    finish: "Pearl white",
    badge: "Best entry",
  },
  {
    slug: "a5",
    name: "Terra Pod A5",
    series: "A Series",
    seriesSlug: "a",
    tagline: "One-bedroom capsule",
    description:
      "A 31 m² capsule with a true bedroom suite, a full kitchen, and a panoramic glazed face — engineered for two to four guests in long-stay comfort.",
    startingPrice: 64300,
    area: "31.4 m²",
    areaSqft: "338 sq ft",
    dimensions: "9500 × 3300 × 3300 mm",
    guests: "2–4 guests",
    weight: "≈6.5 t (with floor heating)",
    power: "6.7 kW · 11.2 kW peak",
    delivery: "12 weeks",
    features: [
      "Custom bar counter",
      "Integrated kitchen with range",
      "Projector + projection screen",
      "Smart voice system",
      "Hollow laminated skylight",
    ],
    exterior: [...baseExterior, "Hollow laminated tempered glass skylight"],
    interior: smartInterior,
    catalogImage: img(2),
    accent: "from-emerald-500/15 to-transparent",
    finish: "Pearl white",
  },
  {
    slug: "a7",
    name: "Terra Pod A7",
    series: "A Series",
    seriesSlug: "a",
    tagline: "Extended capsule",
    description:
      "A 38 m² capsule that extends the A Series silhouette to its most generous proportions — a private bedroom, a separate living core, and a full chef's kitchen.",
    startingPrice: 75600,
    area: "38.0 m²",
    areaSqft: "409 sq ft",
    dimensions: "11500 × 3300 × 3300 mm",
    guests: "2–4 guests",
    weight: "≈8 t (with floor heating)",
    power: "9.9 kW · 15.4 kW peak",
    delivery: "14 weeks",
    features: [
      "Full chef's kitchen",
      "Walk-in wardrobe",
      "Projector + projection screen",
      "International kitchen integrated cabinets",
      "Custom bar counter",
    ],
    exterior: [...baseExterior, "Hollow laminated tempered glass skylight"],
    interior: smartInterior,
    catalogImage: img(3),
    accent: "from-stone-500/20 to-transparent",
    finish: "Pearl white",
  },
  {
    slug: "a9",
    name: "Terra Pod A9",
    series: "A Series",
    seriesSlug: "a",
    tagline: "The flagship capsule",
    description:
      "Our flagship capsule — 45 m² of seamlessly composed living, with a true primary suite, a great-room core, and 13.5 metres of uninterrupted aluminium silhouette.",
    startingPrice: 85500,
    area: "44.6 m²",
    areaSqft: "480 sq ft",
    dimensions: "13500 × 3300 × 3300 mm",
    guests: "2–4 guests",
    weight: "≈10 t (with floor heating)",
    power: "11.5 kW · 17 kW peak",
    delivery: "16 weeks",
    features: [
      "Primary suite",
      "Great-room living core",
      "International chef's kitchen",
      "Custom bar + wardrobe",
      "Projector + projection screen",
    ],
    exterior: [...baseExterior, "Hollow laminated tempered glass skylight"],
    interior: smartInterior,
    catalogImage: img(4),
    accent: "from-accent/20 to-transparent",
    finish: "Pearl white",
    badge: "Flagship",
  },
  {
    slug: "f7",
    name: "Terra Pod F7",
    series: "F Series",
    seriesSlug: "f",
    tagline: "Glass-forward",
    description:
      "An expansive 38 m² pod with a glass-forward elevation and a cantilevered shoulder — designed to dissolve into views.",
    startingPrice: 77450,
    area: "38.0 m²",
    areaSqft: "409 sq ft",
    dimensions: "11500 × 3300 × 3300 mm",
    guests: "2–4 guests",
    weight: "≈8 t (with floor heating)",
    power: "9.9 kW · 15.4 kW peak",
    delivery: "14 weeks",
    features: [
      "Glass-forward elevation",
      "Hard-fitted wardrobe + shoe cabinet",
      "Smart voice system",
      "International kitchen package",
      "Continuous interior datum",
    ],
    exterior: baseExterior,
    interior: smartInterior,
    catalogImage: img(5),
    accent: "from-sky-500/15 to-transparent",
    finish: "Pearl white",
  },
  {
    slug: "h5",
    name: "Terra Pod H5",
    series: "H Series",
    seriesSlug: "h",
    tagline: "Aerodynamic clarity",
    description:
      "A 30 m² pod with a sculpted leading edge and a continuous panoramic skylight. Reads as a single quiet gesture across the site.",
    startingPrice: 70350,
    area: "30.0 m²",
    areaSqft: "323 sq ft",
    dimensions: "9100 × 3300 × 3400 mm",
    guests: "2 guests",
    weight: "≈7 t (with floor heating)",
    power: "10 kW · 15 kW peak",
    delivery: "12 weeks",
    features: [
      "Aerodynamic leading edge",
      "Continuous panoramic skylight",
      "Smart voice control",
      "Bar counter",
      "Hotel-grade access control",
    ],
    exterior: [...baseExterior, "Hollow laminated tempered glass skylight"],
    interior: smartInterior,
    catalogImage: img(6),
    accent: "from-cyan-500/15 to-transparent",
    finish: "Pearl white",
  },
  {
    slug: "r5",
    name: "Terra Pod R5",
    series: "R Series",
    seriesSlug: "r",
    tagline: "Capsule + balcony",
    description:
      "A 30 m² capsule with a stainless-steel entrance door and a panoramic balcony — for sites where you want to step out into the view.",
    startingPrice: 70350,
    area: "30.0 m²",
    areaSqft: "323 sq ft",
    dimensions: "9100 × 3300 × 3400 mm",
    guests: "2 guests",
    weight: "≈7 t (with floor heating)",
    power: "10 kW · 15 kW peak",
    delivery: "12 weeks",
    features: [
      "Panoramic balcony",
      "Stainless steel swing door",
      "Smart voice control",
      "Bar counter",
      "Multi-scenario mode panel",
    ],
    exterior: balconyExterior,
    interior: smartInterior,
    catalogImage: img(7),
    accent: "from-lime-500/15 to-transparent",
    finish: "Pearl white",
  },
  {
    slug: "r7",
    name: "Terra Pod R7",
    series: "R Series",
    seriesSlug: "r",
    tagline: "Extended balcony residence",
    description:
      "A 38 m² R-Series pod with the panoramic balcony, a primary bedroom, and a full living core.",
    startingPrice: 80000,
    area: "38.0 m²",
    areaSqft: "409 sq ft",
    dimensions: "11500 × 3300 × 3400 mm",
    guests: "2–4 guests",
    weight: "≈8 t (with floor heating)",
    power: "10 kW · 15 kW peak",
    delivery: "14 weeks",
    features: [
      "Panoramic balcony",
      "Primary bedroom suite",
      "Stainless steel swing door",
      "Smart voice control",
      "Hotel-grade access",
    ],
    exterior: balconyExterior,
    interior: smartInterior,
    catalogImage: img(8),
    accent: "from-emerald-500/15 to-transparent",
    finish: "Pearl white",
  },
  {
    slug: "p5",
    name: "Terra Pod P5",
    series: "P Series",
    seriesSlug: "p",
    tagline: "Linear precision",
    description:
      "A 31 m² pod with a continuous glazed elevation and a tightly composed interior. The P Series feels long, low, and luminous.",
    startingPrice: 74000,
    area: "31.4 m²",
    areaSqft: "338 sq ft",
    dimensions: "9500 × 3300 × 3200 mm",
    guests: "2 guests",
    weight: "≈6.5 t (with floor heating)",
    power: "7.5 kW · 12 kW peak",
    delivery: "12 weeks",
    features: [
      "Continuous glazed elevation",
      "Hard-fitted wardrobe + shoe cabinet",
      "Range hood / induction cooker",
      "Smart voice control",
      "Multi-scenario mode panel",
    ],
    exterior: balconyExterior,
    interior: smartInterior,
    catalogImage: img(9),
    accent: "from-amber-500/15 to-transparent",
    finish: "Pearl white",
  },
  {
    slug: "p7",
    name: "Terra Pod P7",
    series: "P Series",
    seriesSlug: "p",
    tagline: "Extended P silhouette",
    description:
      "The 38 m² P at full length — a primary bedroom, a generous living core, and the P Series' signature horizontal glazing.",
    startingPrice: 84500,
    area: "38.0 m²",
    areaSqft: "409 sq ft",
    dimensions: "11500 × 3300 × 3200 mm",
    guests: "2–4 guests",
    weight: "≈8 t (with floor heating)",
    power: "11.5 kW · 17 kW peak",
    delivery: "14 weeks",
    features: [
      "Primary bedroom suite",
      "International kitchen package",
      "Hard-fitted wardrobe",
      "Smart voice control",
      "Hotel-grade access",
    ],
    exterior: balconyExterior,
    interior: smartInterior,
    catalogImage: img(10),
    accent: "from-orange-500/15 to-transparent",
    finish: "Pearl white",
  },
  {
    slug: "z5",
    name: "Terra Pod Z5",
    series: "Z Series",
    seriesSlug: "z",
    tagline: "Architectural minimalism",
    description:
      "A 31 m² Z — tightly composed proportions and a hard horizon line. Suited to clients who want the pod to disappear into the site.",
    startingPrice: 73200,
    area: "31.4 m²",
    areaSqft: "338 sq ft",
    dimensions: "9500 × 3300 × 3200 mm",
    guests: "2 guests",
    weight: "≈6.5 t (with floor heating)",
    power: "7.5 kW · 12 kW peak",
    delivery: "12 weeks",
    features: [
      "Hard-horizon roofline",
      "International kitchen package",
      "Hard-fitted wardrobe + shoe cabinet",
      "Smart voice control",
      "Hotel-grade access",
    ],
    exterior: balconyExterior,
    interior: smartInterior,
    catalogImage: img(11),
    accent: "from-stone-500/15 to-transparent",
    finish: "Pearl white",
  },
  {
    slug: "z7",
    name: "Terra Pod Z7",
    series: "Z Series",
    seriesSlug: "z",
    tagline: "Extended Z residence",
    description:
      "A 38 m² Z — the most architectural expression in the collection at this length. A primary suite, a living core, and a horizon line that holds.",
    startingPrice: 86600,
    area: "38.0 m²",
    areaSqft: "409 sq ft",
    dimensions: "11500 × 3300 × 3200 mm",
    guests: "2–4 guests",
    weight: "≈8 t (with floor heating)",
    power: "11.5 kW · 17 kW peak",
    delivery: "14 weeks",
    features: [
      "Hard-horizon roofline",
      "Primary suite",
      "International chef's kitchen",
      "Smart voice control",
      "Hotel-grade access",
    ],
    exterior: balconyExterior,
    interior: smartInterior,
    catalogImage: img(12),
    accent: "from-zinc-500/15 to-transparent",
    finish: "Pearl white",
  },
  {
    slug: "e3-ii",
    name: "Terra Pod E3-II",
    series: "E-II Series",
    seriesSlug: "e",
    tagline: "Compact studio",
    description:
      "A second-generation E shell at studio scale — 14.6 m² of refined detail, with a continuous interior datum line and deeper insulation.",
    startingPrice: 49400,
    area: "14.6 m²",
    areaSqft: "157 sq ft",
    dimensions: "5600 × 2600 × 3200 mm",
    guests: "2 guests",
    weight: "≈4 t (with floor heating)",
    power: "6.7 kW · 8.2 kW peak",
    delivery: "10 weeks",
    features: [
      "Refined snout silhouette",
      "Deeper thermal envelope",
      "Smart voice system",
      "Starry-sky skylight option",
      "Continuous interior datum",
    ],
    exterior: baseExterior,
    interior: baseInterior,
    catalogImage: img(13),
    accent: "from-amber-500/15 to-transparent",
    finish: "Pearl white",
  },
  {
    slug: "e5-ii",
    name: "Terra Pod E5-II",
    series: "E-II Series",
    seriesSlug: "e",
    tagline: "Mid E-II",
    description:
      "A 27 m² E-II — a balcony-ready entrance, a panoramic skylight, and the second-generation interior package.",
    startingPrice: 67800,
    area: "27.2 m²",
    areaSqft: "293 sq ft",
    dimensions: "8500 × 3200 × 3200 mm",
    guests: "2 guests",
    weight: "≈6.5 t (with floor heating)",
    power: "6.7 kW · 8.2 kW peak",
    delivery: "12 weeks",
    features: [
      "Panoramic skylight",
      "Stainless steel swing door",
      "Custom bar counter",
      "Smart voice system",
      "Projector option",
    ],
    exterior: balconyExterior,
    interior: baseInterior,
    catalogImage: img(14),
    accent: "from-emerald-500/15 to-transparent",
    finish: "Pearl white",
  },
  {
    slug: "e6-ii",
    name: "Terra Pod E6-II",
    series: "E-II Series",
    seriesSlug: "e",
    tagline: "E-II with kitchen",
    description:
      "A 27 m² E-II with the international integrated kitchen package — for clients who want the pod to live as a primary residence.",
    startingPrice: 65350,
    area: "27.2 m²",
    areaSqft: "293 sq ft",
    dimensions: "8500 × 3200 × 3200 mm",
    guests: "2 guests",
    weight: "≈6.5 t (with floor heating)",
    power: "6.7 kW · 8.2 kW peak",
    delivery: "12 weeks",
    features: [
      "International kitchen package",
      "Range hood / induction cooker",
      "Smart voice system",
      "Custom bar counter",
      "Projector option",
    ],
    exterior: baseExterior,
    interior: smartInterior,
    catalogImage: img(15),
    accent: "from-teal-500/15 to-transparent",
    finish: "Pearl white",
  },
  {
    slug: "e7-ii",
    name: "Terra Pod E7-II",
    series: "E-II Series",
    seriesSlug: "e",
    tagline: "Flagship E-II",
    description:
      "The most generous E-II — 36.8 m² with a primary suite, a panoramic balcony, and a fully integrated kitchen.",
    startingPrice: 79500,
    area: "36.8 m²",
    areaSqft: "396 sq ft",
    dimensions: "11500 × 3200 × 3200 mm",
    guests: "2–4 guests",
    weight: "≈8 t (with floor heating)",
    power: "9.9 kW · 11.3 kW peak",
    delivery: "14 weeks",
    features: [
      "Primary suite",
      "Panoramic balcony",
      "International kitchen package",
      "Smart voice system",
      "Projector + projection screen",
    ],
    exterior: balconyExterior,
    interior: smartInterior,
    catalogImage: img(16),
    accent: "from-amber-500/20 to-transparent",
    finish: "Pearl white",
  },
  {
    slug: "w3",
    name: "Terra Pod W3",
    series: "W Series",
    seriesSlug: "w",
    tagline: "Compact, residential",
    description:
      "A 19 m² W with squared corners and a residential proportion. Reads as architecture rather than as a pod.",
    startingPrice: 58800,
    area: "19.1 m²",
    areaSqft: "206 sq ft",
    dimensions: "5600 × 3400 × 3400 mm",
    guests: "2 guests",
    weight: "≈4 t (with floor heating)",
    power: "6.7 kW · 11.2 kW peak",
    delivery: "10 weeks",
    features: [
      "Squared residential proportions",
      "Smart voice control",
      "Electric towel rack",
      "Micro-ventilation window",
      "Hotel-grade access",
    ],
    exterior: baseExterior,
    interior: smartInterior,
    catalogImage: img(17),
    accent: "from-stone-500/20 to-transparent",
    finish: "Pearl white",
  },
  {
    slug: "w6",
    name: "Terra Pod W6",
    series: "W Series",
    seriesSlug: "w",
    tagline: "Mid W residence",
    description:
      "A 32 m² W — a fully equipped kitchen, a laundry zone, and a primary bedroom.",
    startingPrice: 79500,
    area: "32.3 m²",
    areaSqft: "348 sq ft",
    dimensions: "9500 × 3400 × 3400 mm",
    guests: "2–4 guests",
    weight: "≈6.5 t (with floor heating)",
    power: "6.7 kW · 11.2 kW peak",
    delivery: "12 weeks",
    features: [
      "Custom bar counter / wardrobe",
      "Range hood / induction cooker",
      "Washing machine package",
      "Smart voice system",
      "Projector + projection screen",
    ],
    exterior: baseExterior,
    interior: smartInterior,
    catalogImage: img(18),
    accent: "from-stone-500/20 to-transparent",
    finish: "Pearl white",
  },
  {
    slug: "w9",
    name: "Terra Pod W9",
    series: "W Series",
    seriesSlug: "w",
    tagline: "Flagship W residence",
    description:
      "The W Series at full residential scale — 39 m², a primary suite, a great-room kitchen, and a full laundry.",
    startingPrice: 97100,
    area: "39.1 m²",
    areaSqft: "421 sq ft",
    dimensions: "11500 × 3400 × 3400 mm",
    guests: "2–4 guests",
    weight: "≈8 t (with floor heating)",
    power: "9.9 kW · 15.4 kW peak",
    delivery: "14 weeks",
    features: [
      "Primary suite",
      "Great-room kitchen",
      "Full laundry package",
      "Custom bar / wardrobe",
      "Smart voice system",
    ],
    exterior: baseExterior,
    interior: smartInterior,
    catalogImage: img(19),
    accent: "from-stone-500/20 to-transparent",
    finish: "Pearl white",
    badge: "Residential",
  },
  {
    slug: "a7s",
    name: "Terra Pod A7S",
    series: "Specialty",
    seriesSlug: "specialty",
    tagline: "Service Center",
    description:
      "A hospitality service center in oxide red — front desk, lounge, and bathrooms — engineered to land beside your accommodation pods.",
    startingPrice: 84500,
    area: "38.0 m²",
    areaSqft: "409 sq ft",
    dimensions: "11500 × 3300 × 3300 mm",
    guests: "2–4 staff",
    weight: "≈8 t (with floor heating)",
    power: "9.9 kW · 15.4 kW peak",
    delivery: "14 weeks",
    features: [
      "Custom front desk",
      "Lounge swing door",
      "Two branded toilets",
      "Sliding glass entrance door",
      "Insulated tempered glazing",
    ],
    exterior: [...baseExterior, "Sliding glass entrance door"],
    interior: [
      ...baseInterior,
      "Custom front desk",
      "Custom wall cabinet",
      "Lounge zone",
    ],
    catalogImage: img(20),
    accent: "from-red-700/30 to-transparent",
    finish: "Oxide red",
    badge: "Hospitality",
  },
  {
    slug: "a9d",
    name: "Terra Pod A9D",
    series: "Specialty",
    seriesSlug: "specialty",
    tagline: "Dining Room",
    description:
      "A 45 m² hospitality dining capsule in oxide red — a full bar, a chef's kitchen, and a dining room engineered for service.",
    startingPrice: 93700,
    area: "44.6 m²",
    areaSqft: "480 sq ft",
    dimensions: "13500 × 3300 × 3300 mm",
    guests: "2–4 staff",
    weight: "≈9 t (with floor heating)",
    power: "11.5 kW · 17 kW peak",
    delivery: "16 weeks",
    features: [
      "Custom bar counter",
      "Chef's kitchen package",
      "Sunshade roller blind",
      "Sliding glass entrance door",
      "Smart voice system",
    ],
    exterior: [...baseExterior, "Sliding glass entrance door"],
    interior: [
      ...baseInterior,
      "Custom bar / display wall cabinets",
      "Custom kitchen countertop",
      "Tile floor in bar area",
    ],
    catalogImage: img(21),
    accent: "from-red-700/30 to-transparent",
    finish: "Oxide red",
    badge: "Hospitality",
  },
  {
    slug: "ae23-a",
    name: "Terra Pod AE23-A",
    series: "AE Cabin Series",
    seriesSlug: "ae",
    tagline: "Compact cabin",
    description:
      "A 23 m² panelised cabin with a solar-ready roof, Low-E tempered glazing, and a kit-of-parts wall module that ships flat and assembles in days.",
    startingPrice: 72700,
    area: "23.0 m²",
    areaSqft: "248 sq ft",
    dimensions: "6500 × 3480 × 3300 mm",
    guests: "2 guests",
    weight: "≈4.3 t",
    power: "Solar-ready · grid-tie",
    delivery: "12 weeks",
    features: [
      "Solar panel mounting clips",
      "PVDF-coated aluminium roof",
      "Low-E tempered glazing",
      "8 mm carbon-crystal wall panel",
      "Modular bathroom package",
    ],
    exterior: [
      "PVDF-coated aluminium roof plate",
      "Light steel galvanised structural frame",
      "PIR flame-retardant insulation",
      "8 mm decorative wall panel",
      "Hot-dip galvanised steel base",
    ],
    interior: [
      "Insulated Low-E tempered glass",
      "Modular bathroom",
      "Toilet + water tank, vanity, wall cabinet",
      "Shower faucet + rod, towel rack",
      "Exhaust fan, LED lights, floor drain",
    ],
    catalogImage: img(22),
    accent: "from-moss/30 to-transparent",
    finish: "Cabin oak",
  },
  {
    slug: "ae31-a",
    name: "Terra Pod AE31-A",
    series: "AE Cabin Series",
    seriesSlug: "ae",
    tagline: "31 m² cabin · plan A",
    description:
      "A 31 m² AE cabin in plan A — a primary bedroom, a living core, and a service zone.",
    startingPrice: 93500,
    area: "31.1 m²",
    areaSqft: "335 sq ft",
    dimensions: "8940 × 3480 × 3300 mm",
    guests: "2 guests",
    weight: "≈5.5 t",
    power: "Solar-ready · grid-tie",
    delivery: "14 weeks",
    features: [
      "Plan A: bedroom + living + service",
      "Solar panel mounting clips",
      "8 mm carbon-crystal wall panel",
      "Modular bathroom",
      "Optional kitchen package",
    ],
    exterior: [
      "PVDF-coated aluminium roof plate",
      "Light steel galvanised structural frame",
      "PIR flame-retardant insulation",
      "8 mm decorative wall panel",
      "Hot-dip galvanised steel base",
    ],
    interior: [
      "Insulated Low-E tempered glass",
      "Modular bathroom",
      "Optional kitchen + appliances",
      "LED lighting, floor drain",
    ],
    catalogImage: img(23),
    accent: "from-moss/30 to-transparent",
    finish: "Cabin oak",
  },
  {
    slug: "ae31-b",
    name: "Terra Pod AE31-B",
    series: "AE Cabin Series",
    seriesSlug: "ae",
    tagline: "31 m² cabin · plan B",
    description:
      "Plan B of the 31 m² AE — the same shell, with a reconfigured interior optimized for a couple plus a child or workspace.",
    startingPrice: 93500,
    area: "31.1 m²",
    areaSqft: "335 sq ft",
    dimensions: "8940 × 3480 × 3300 mm",
    guests: "2–3 guests",
    weight: "≈5.5 t",
    power: "Solar-ready · grid-tie",
    delivery: "14 weeks",
    features: [
      "Plan B: split-zone configuration",
      "Solar panel mounting clips",
      "8 mm carbon-crystal wall panel",
      "Modular bathroom",
      "Optional kitchen package",
    ],
    exterior: [
      "PVDF-coated aluminium roof plate",
      "Light steel galvanised structural frame",
      "PIR flame-retardant insulation",
      "8 mm decorative wall panel",
      "Hot-dip galvanised steel base",
    ],
    interior: [
      "Insulated Low-E tempered glass",
      "Modular bathroom",
      "Optional kitchen + appliances",
      "LED lighting, floor drain",
    ],
    catalogImage: img(24),
    accent: "from-moss/30 to-transparent",
    finish: "Cabin oak",
  },
  {
    slug: "ae40-a",
    name: "Terra Pod AE40-A",
    series: "AE Cabin Series",
    seriesSlug: "ae",
    tagline: "40 m² cabin · plan A",
    description:
      "A 40 m² AE cabin — a true two-zone residence with a primary suite, an open kitchen-living core, and a covered terrace zone.",
    startingPrice: 115200,
    area: "39.6 m²",
    areaSqft: "426 sq ft",
    dimensions: "11380 × 3480 × 3300 mm",
    guests: "2–4 guests",
    weight: "≈6.7 t",
    power: "Solar-ready · grid-tie",
    delivery: "16 weeks",
    features: [
      "Plan A: bedroom + open kitchen-living",
      "Solar panel mounting clips",
      "8 mm carbon-crystal wall panel",
      "Modular bathroom",
      "Optional kitchen package",
    ],
    exterior: [
      "PVDF-coated aluminium roof plate",
      "Light steel galvanised structural frame",
      "PIR flame-retardant insulation",
      "8 mm decorative wall panel",
      "Hot-dip galvanised steel base",
    ],
    interior: [
      "Insulated Low-E tempered glass",
      "Modular bathroom",
      "Optional kitchen + appliances",
      "LED lighting, floor drain",
    ],
    catalogImage: img(25),
    accent: "from-moss/30 to-transparent",
    finish: "Cabin oak",
    badge: "Cabin flagship",
  },
  {
    slug: "ae40-b",
    name: "Terra Pod AE40-B",
    series: "AE Cabin Series",
    seriesSlug: "ae",
    tagline: "40 m² cabin · plan B",
    description:
      "Plan B of the 40 m² AE — a reconfigured layout with a separated dining zone and an enlarged primary suite.",
    startingPrice: 115200,
    area: "39.6 m²",
    areaSqft: "426 sq ft",
    dimensions: "11380 × 3480 × 3300 mm",
    guests: "2–4 guests",
    weight: "≈6.7 t",
    power: "Solar-ready · grid-tie",
    delivery: "16 weeks",
    features: [
      "Plan B: separated dining + primary",
      "Solar panel mounting clips",
      "8 mm carbon-crystal wall panel",
      "Modular bathroom",
      "Optional kitchen package",
    ],
    exterior: [
      "PVDF-coated aluminium roof plate",
      "Light steel galvanised structural frame",
      "PIR flame-retardant insulation",
      "8 mm decorative wall panel",
      "Hot-dip galvanised steel base",
    ],
    interior: [
      "Insulated Low-E tempered glass",
      "Modular bathroom",
      "Optional kitchen + appliances",
      "LED lighting, floor drain",
    ],
    catalogImage: img(26),
    accent: "from-moss/30 to-transparent",
    finish: "Cabin oak",
  },
];

export const galleryImages = models.map((m) => ({
  src: m.catalogImage,
  name: m.name,
  series: m.series,
  slug: m.slug,
}));

export function getModel(slug: string): Model | undefined {
  return models.find((m) => m.slug === slug);
}

export function getSeriesModels(seriesSlug: string): Model[] {
  return models.filter((m) => m.seriesSlug === seriesSlug);
}

export function getSeries(seriesSlug: string): Series | undefined {
  return series.find((s) => s.slug === seriesSlug);
}
